_merge: deep
theme: osuny
params:
  additional_csp: 'osunystaging-1b4da.kxcdn.com'
  keycdn:
    url: https://osunystaging-1b4da.kxcdn.com
  summary:
    position: hero
  search:
    active: false
  single:
    navigation:
      active: false
